---
name: Checks

on: [push]

jobs:
  test-lint: # job id
    name: Test and Lint
    runs-on: ubuntu-20.04 # OS
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1 # we reuse a build action in github
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Checkout # we checkout (access the code) for github job to apply test and linting
        uses: actions/checkout@v2
      - name: Test
        run: docker-compose run --rm app sh -c "python manage.py test"
      - name: Lint
        run: docker-composer run --rm app sh -c "flake8"
